version: "3.9"

volumes:
  postgres_data:

services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: sidorenkov_204
      POSTGRES_USER: sidorenkov_204
      POSTGRES_PASSWORD: sidorenkov_204
      PGDATA: /var/lib/postgresql/data/pgdata-olympics
    volumes:
      - ./db/docker/db/scripts/olympics.sql:/docker-entrypoint-initdb.d/olympics.sql
      - ./db/dz:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 1s
      retries: 5

  amigo:
    build: ./amigo
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./amigo/.docker.env

  krusty:
    build: ./krusty
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./krusty/.docker.env
