[package]
name = "krusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = {version="2.0.2", features=["postgres"]}
#sqlx = "0.6.2"
dotenv = "0.15.0"
